blank_issues_enabled: true
contact_links:
  - name: "\U0001F4DA ModernFlyouts user documentation"
    url: https://modernflyouts-community.github.io/docs/#/
    about: Documentation for users of ModernFlyouts
  - name: "\U0001F4DA ModernFlyouts dev documentation"
    url: https://modernflyouts-community.github.io/docs/#/
    about: Documentation for people interested in developing and contributing for ModernFlyouts
