//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernFlyouts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernFlyouts.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airplane Mode is not available :(.
        /// </summary>
        public static string AirplaneMode_NotAvailable {
            get {
                return ResourceManager.GetString("AirplaneMode.NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airplane mode off.
        /// </summary>
        public static string AirplaneModeOff {
            get {
                return ResourceManager.GetString("AirplaneModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airplane mode on.
        /// </summary>
        public static string AirplaneModeOn {
            get {
                return ResourceManager.GetString("AirplaneModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align to default position.
        /// </summary>
        public static string Align {
            get {
                return ResourceManager.GetString("Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connected Audio Devices.
        /// </summary>
        public static string AudioFlyoutHelper_NoDevices {
            get {
                return ResourceManager.GetString("AudioFlyoutHelper.NoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModernFlyouts.
        /// </summary>
        public static string Enums_DefaultFlyout_ModernFlyouts {
            get {
                return ResourceManager.GetString("Enums.DefaultFlyout.ModernFlyouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enums_DefaultFlyout_None {
            get {
                return ResourceManager.GetString("Enums.DefaultFlyout.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows default.
        /// </summary>
        public static string Enums_DefaultFlyout_WindowsDefault {
            get {
                return ResourceManager.GetString("Enums.DefaultFlyout.WindowsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Enums_Orientation_Horizontal {
            get {
                return ResourceManager.GetString("Enums.Orientation.Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Enums_Orientation_Vertical {
            get {
                return ResourceManager.GetString("Enums.Orientation.Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitItem {
            get {
                return ResourceManager.GetString("ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the app safely.
        /// </summary>
        public static string ExitItemDescription {
            get {
                return ResourceManager.GetString("ExitItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Mode.
        /// </summary>
        public static string LockKeysFlyoutHelper_InsertMode {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.InsertMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is off.
        /// </summary>
        public static string LockKeysFlyoutHelper_KeyIsOff {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.KeyIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is on.
        /// </summary>
        public static string LockKeysFlyoutHelper_KeyIsOn {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.KeyIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtype Mode.
        /// </summary>
        public static string LockKeysFlyoutHelper_OvertypeMode {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.OvertypeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin TopBar.
        /// </summary>
        public static string PinTopBar {
            get {
                return ResourceManager.GetString("PinTopBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the point in the format &apos;X,Y&apos; (for e.g. 50,60)..
        /// </summary>
        public static string PointValidationRule_PointFormatInvalidMessage {
            get {
                return ResourceManager.GetString("PointValidationRule.PointFormatInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter X,Y values in the range {0} - {1}..
        /// </summary>
        public static string PointValidationRule_PointOutOfRangeMessage {
            get {
                return ResourceManager.GetString("PointValidationRule.PointOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be coverted to string..
        /// </summary>
        public static string PointValidationRule_StringConvertionErrorMessage {
            get {
                return ResourceManager.GetString("PointValidationRule.StringConvertionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Default.
        /// </summary>
        public static string RestoreDefaultItem {
            get {
                return ResourceManager.GetString("RestoreDefaultItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores the windows default flyout and safely quits this app.
        /// </summary>
        public static string RestoreDefaultItemDescription {
            get {
                return ResourceManager.GetString("RestoreDefaultItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Controls.
        /// </summary>
        public static string SessionControl_MoreControls {
            get {
                return ResourceManager.GetString("SessionControl.MoreControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SessionControl_Next {
            get {
                return ResourceManager.GetString("SessionControl.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string SessionControl_Pause {
            get {
                return ResourceManager.GetString("SessionControl.Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string SessionControl_Play {
            get {
                return ResourceManager.GetString("SessionControl.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string SessionControl_Previous {
            get {
                return ResourceManager.GetString("SessionControl.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat: all.
        /// </summary>
        public static string SessionControl_RepeatAll {
            get {
                return ResourceManager.GetString("SessionControl.RepeatAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat: off.
        /// </summary>
        public static string SessionControl_RepeatOff {
            get {
                return ResourceManager.GetString("SessionControl.RepeatOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat: one.
        /// </summary>
        public static string SessionControl_RepeatOne {
            get {
                return ResourceManager.GetString("SessionControl.RepeatOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle: off.
        /// </summary>
        public static string SessionControl_ShuffleOff {
            get {
                return ResourceManager.GetString("SessionControl.ShuffleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle: on.
        /// </summary>
        public static string SessionControl_ShuffleOn {
            get {
                return ResourceManager.GetString("SessionControl.ShuffleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string SessionControl_Stop {
            get {
                return ResourceManager.GetString("SessionControl.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline Info.
        /// </summary>
        public static string SessionControl_TimelineInfo {
            get {
                return ResourceManager.GetString("SessionControl.TimelineInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string Settings_Additional {
            get {
                return ResourceManager.GetString("Settings.Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Settings_Behavior {
            get {
                return ResourceManager.GetString("Settings.Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Flyout.
        /// </summary>
        public static string Settings_DefaultFlyout {
            get {
                return ResourceManager.GetString("Settings.DefaultFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the default flyout.
        /// </summary>
        public static string Settings_DefaultFlyoutDescription {
            get {
                return ResourceManager.GetString("Settings.DefaultFlyoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing the Windows Default Flyout as default won&apos;t close this app. This app will still keep running in the background. Please exit this app safely to improve performance..
        /// </summary>
        public static string Settings_DefaultFlyoutWarningMessage {
            get {
                return ResourceManager.GetString("Settings.DefaultFlyoutWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Settings_Disabled {
            get {
                return ResourceManager.GetString("Settings.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Settings_Enabled {
            get {
                return ResourceManager.GetString("Settings.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout Background Opacity.
        /// </summary>
        public static string Settings_FlyoutBackgroundOpacity {
            get {
                return ResourceManager.GetString("Settings.FlyoutBackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout Default Position (for Align button).
        /// </summary>
        public static string Settings_FlyoutDefaultPosition {
            get {
                return ResourceManager.GetString("Settings.FlyoutDefaultPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the position in &apos;X,Y&apos; format (for e.g. 50,60).
        /// </summary>
        public static string Settings_FlyoutDefaultPositionDescription {
            get {
                return ResourceManager.GetString("Settings.FlyoutDefaultPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout TopBar.
        /// </summary>
        public static string Settings_FlyoutTopBar {
            get {
                return ResourceManager.GetString("Settings.FlyoutTopBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the app to change the language properly.
        /// </summary>
        public static string Settings_LanguageDescription {
            get {
                return ResourceManager.GetString("Settings.LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Number of Media Session Controls to show vertically.
        /// </summary>
        public static string Settings_MaxVerticalSessionControlsCount {
            get {
                return ResourceManager.GetString("Settings.MaxVerticalSessionControlsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Settings_Modules {
            get {
                return ResourceManager.GetString("Settings.Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirplaneMode-flyout Module.
        /// </summary>
        public static string Settings_Modules_Airplane {
            get {
                return ResourceManager.GetString("Settings.Modules.Airplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio-flyout Module.
        /// </summary>
        public static string Settings_Modules_Audio {
            get {
                return ResourceManager.GetString("Settings.Modules.Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness-flyout Module.
        /// </summary>
        public static string Settings_Modules_Brightness {
            get {
                return ResourceManager.GetString("Settings.Modules.Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LockKeys-flyout Module.
        /// </summary>
        public static string Settings_Modules_LockKeys {
            get {
                return ResourceManager.GetString("Settings.Modules.LockKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup.
        /// </summary>
        public static string Settings_RunAtStartup {
            get {
                return ResourceManager.GetString("Settings.RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Sessions Panel Orientation.
        /// </summary>
        public static string Settings_SessionsPanelOrientation {
            get {
                return ResourceManager.GetString("Settings.SessionsPanelOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Global System Media Transport (Media) Controls in Volume flyout.
        /// </summary>
        public static string Settings_ShowGSMTCInVolumeFlyout {
            get {
                return ResourceManager.GetString("Settings.ShowGSMTCInVolumeFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Volume control in Global System Media Transport (Media) Controls flyout.
        /// </summary>
        public static string Settings_ShowVolumeControlInGSMTCFlyout {
            get {
                return ResourceManager.GetString("Settings.ShowVolumeControlInGSMTCFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        public static string Settings_SystemDefault {
            get {
                return ResourceManager.GetString("Settings.SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray Icon Mode.
        /// </summary>
        public static string Settings_TrayIconMode {
            get {
                return ResourceManager.GetString("Settings.TrayIconMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colored.
        /// </summary>
        public static string Settings_TrayIconMode_Colored {
            get {
                return ResourceManager.GetString("Settings.TrayIconMode.Colored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome.
        /// </summary>
        public static string Settings_TrayIconMode_Monochrome {
            get {
                return ResourceManager.GetString("Settings.TrayIconMode.Monochrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsItem {
            get {
                return ResourceManager.GetString("SettingsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings window.
        /// </summary>
        public static string SettingsItemDescription {
            get {
                return ResourceManager.GetString("SettingsItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin TopBar.
        /// </summary>
        public static string UnpinTopBar {
            get {
                return ResourceManager.GetString("UnpinTopBar", resourceCulture);
            }
        }
    }
}
