//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernFlyouts.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModernFlyouts.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is designed to be a modern Fluent Design replacement for the old metro themed flyouts present in Windows since Windows 8..
        /// </summary>
        public static string About_AppDescription {
            get {
                return ResourceManager.GetString("About.AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributors.
        /// </summary>
        public static string About_Contributors {
            get {
                return ResourceManager.GetString("About.Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string About_Dependencies {
            get {
                return ResourceManager.GetString("About.Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you find any bugs, please open a new issue in the github repository..
        /// </summary>
        public static string About_FileABug {
            get {
                return ResourceManager.GetString("About.FileABug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub repository.
        /// </summary>
        public static string About_GitHub {
            get {
                return ResourceManager.GetString("About.GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a new issue.
        /// </summary>
        public static string About_OpenNewIssue {
            get {
                return ResourceManager.GetString("About.OpenNewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and Review on Microsoft Store.
        /// </summary>
        public static string About_RateAndReview {
            get {
                return ResourceManager.GetString("About.RateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version : .
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About.Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airplane mode is not available :(.
        /// </summary>
        public static string AirplaneMode_NotAvailable {
            get {
                return ResourceManager.GetString("AirplaneMode.NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airplane mode off.
        /// </summary>
        public static string AirplaneModeOff {
            get {
                return ResourceManager.GetString("AirplaneModeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airplane mode on.
        /// </summary>
        public static string AirplaneModeOn {
            get {
                return ResourceManager.GetString("AirplaneModeOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align to default position.
        /// </summary>
        public static string Align {
            get {
                return ResourceManager.GetString("Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of sessions to show.
        /// </summary>
        public static string AudioFlyoutHelper_MaxVerticalSessionControlsCount {
            get {
                return ResourceManager.GetString("AudioFlyoutHelper.MaxVerticalSessionControlsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connected Audio Devices.
        /// </summary>
        public static string AudioFlyoutHelper_NoDevices {
            get {
                return ResourceManager.GetString("AudioFlyoutHelper.NoDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media sessions panel orientation.
        /// </summary>
        public static string AudioFlyoutHelper_SessionsPanelOrientation {
            get {
                return ResourceManager.GetString("AudioFlyoutHelper.SessionsPanelOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Global System Media Transport Controls (GSMTC) aka Media controls in Volume flyout.
        /// </summary>
        public static string AudioFlyoutHelper_ShowGSMTCInVolumeFlyout {
            get {
                return ResourceManager.GetString("AudioFlyoutHelper.ShowGSMTCInVolumeFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Volume control in Global System Media Transport Controls (GSMTC) aka Media flyout.
        /// </summary>
        public static string AudioFlyoutHelper_ShowVolumeControlInGSMTCFlyout {
            get {
                return ResourceManager.GetString("AudioFlyoutHelper.ShowVolumeControlInGSMTCFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail alignment.
        /// </summary>
        public static string AudioFlyoutHelper_ThumbnailAlignment {
            get {
                return ResourceManager.GetString("AudioFlyoutHelper.ThumbnailAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModernFlyouts.
        /// </summary>
        public static string Enums_DefaultFlyout_ModernFlyouts {
            get {
                return ResourceManager.GetString("Enums.DefaultFlyout.ModernFlyouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enums_DefaultFlyout_None {
            get {
                return ResourceManager.GetString("Enums.DefaultFlyout.None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows default.
        /// </summary>
        public static string Enums_DefaultFlyout_WindowsDefault {
            get {
                return ResourceManager.GetString("Enums.DefaultFlyout.WindowsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Enums_ElementTheme_Dark {
            get {
                return ResourceManager.GetString("Enums.ElementTheme.Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Enums_ElementTheme_Light {
            get {
                return ResourceManager.GetString("Enums.ElementTheme.Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        public static string Enums_Orientation_Horizontal {
            get {
                return ResourceManager.GetString("Enums.Orientation.Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        public static string Enums_Orientation_Vertical {
            get {
                return ResourceManager.GetString("Enums.Orientation.Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-hide.
        /// </summary>
        public static string Enums_TopBarVisibility_AutoHide {
            get {
                return ResourceManager.GetString("Enums.TopBarVisibility.AutoHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsed.
        /// </summary>
        public static string Enums_TopBarVisibility_Collapsed {
            get {
                return ResourceManager.GetString("Enums.TopBarVisibility.Collapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string Enums_TopBarVisibility_Visible {
            get {
                return ResourceManager.GetString("Enums.TopBarVisibility.Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitItem {
            get {
                return ResourceManager.GetString("ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the app safely.
        /// </summary>
        public static string ExitItemDescription {
            get {
                return ResourceManager.GetString("ExitItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps lock.
        /// </summary>
        public static string LockKeysFlyoutHelper_CapsLock {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.CapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string LockKeysFlyoutHelper_Insert {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Mode.
        /// </summary>
        public static string LockKeysFlyoutHelper_InsertMode {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.InsertMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is off.
        /// </summary>
        public static string LockKeysFlyoutHelper_KeyIsOff {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.KeyIsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is on.
        /// </summary>
        public static string LockKeysFlyoutHelper_KeyIsOn {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.KeyIsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num lock.
        /// </summary>
        public static string LockKeysFlyoutHelper_NumLock {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.NumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtype Mode.
        /// </summary>
        public static string LockKeysFlyoutHelper_OvertypeMode {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.OvertypeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll lock.
        /// </summary>
        public static string LockKeysFlyoutHelper_ScrollLock {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.ScrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the keys you want to show the flyout for.
        /// </summary>
        public static string LockKeysFlyoutHelper_SelectKeyDescription {
            get {
                return ResourceManager.GetString("LockKeysFlyoutHelper.SelectKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ngs.Settings_Reset}.
        /// </summary>
        public static string NgsSettings_Reset {
            get {
                return ResourceManager.GetString("NgsSettings_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin TopBar.
        /// </summary>
        public static string PinTopBar {
            get {
                return ResourceManager.GetString("PinTopBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the point in the format &apos;X,Y&apos; (for e.g. 50,60)..
        /// </summary>
        public static string PointValidationRule_PointFormatInvalidMessage {
            get {
                return ResourceManager.GetString("PointValidationRule.PointFormatInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter X,Y values in the range {0} - {1}..
        /// </summary>
        public static string PointValidationRule_PointOutOfRangeMessage {
            get {
                return ResourceManager.GetString("PointValidationRule.PointOutOfRangeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be coverted to string..
        /// </summary>
        public static string PointValidationRule_StringConvertionErrorMessage {
            get {
                return ResourceManager.GetString("PointValidationRule.StringConvertionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore legacy flyout.
        /// </summary>
        public static string RestoreDefaultItem {
            get {
                return ResourceManager.GetString("RestoreDefaultItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores the windows default flyout and safely quits this app.
        /// </summary>
        public static string RestoreDefaultItemDescription {
            get {
                return ResourceManager.GetString("RestoreDefaultItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Controls.
        /// </summary>
        public static string SessionControl_MoreControls {
            get {
                return ResourceManager.GetString("SessionControl.MoreControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SessionControl_Next {
            get {
                return ResourceManager.GetString("SessionControl.Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string SessionControl_Pause {
            get {
                return ResourceManager.GetString("SessionControl.Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string SessionControl_Play {
            get {
                return ResourceManager.GetString("SessionControl.Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string SessionControl_Previous {
            get {
                return ResourceManager.GetString("SessionControl.Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat: all.
        /// </summary>
        public static string SessionControl_RepeatAll {
            get {
                return ResourceManager.GetString("SessionControl.RepeatAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat: off.
        /// </summary>
        public static string SessionControl_RepeatOff {
            get {
                return ResourceManager.GetString("SessionControl.RepeatOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat: one.
        /// </summary>
        public static string SessionControl_RepeatOne {
            get {
                return ResourceManager.GetString("SessionControl.RepeatOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle: off.
        /// </summary>
        public static string SessionControl_ShuffleOff {
            get {
                return ResourceManager.GetString("SessionControl.ShuffleOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle: on.
        /// </summary>
        public static string SessionControl_ShuffleOn {
            get {
                return ResourceManager.GetString("SessionControl.ShuffleOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string SessionControl_Stop {
            get {
                return ResourceManager.GetString("SessionControl.Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline Info.
        /// </summary>
        public static string SessionControl_TimelineInfo {
            get {
                return ResourceManager.GetString("SessionControl.TimelineInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string Settings_Additional {
            get {
                return ResourceManager.GetString("Settings.Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align flyout to this position.
        /// </summary>
        public static string Settings_AlignFlyout {
            get {
                return ResourceManager.GetString("Settings.AlignFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings.Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme.
        /// </summary>
        public static string Settings_AppTheme {
            get {
                return ResourceManager.GetString("Settings.AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        public static string Settings_Behavior {
            get {
                return ResourceManager.GetString("Settings.Behavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Flyout.
        /// </summary>
        public static string Settings_DefaultFlyout {
            get {
                return ResourceManager.GetString("Settings.DefaultFlyout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the default flyout.
        /// </summary>
        public static string Settings_DefaultFlyoutDescription {
            get {
                return ResourceManager.GetString("Settings.DefaultFlyoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing the Windows Default Flyout as default won&apos;t close this app. This app will still keep running in the background. Please exit this app safely to improve performance..
        /// </summary>
        public static string Settings_DefaultFlyoutWarningMessage {
            get {
                return ResourceManager.GetString("Settings.DefaultFlyoutWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Settings_Disabled {
            get {
                return ResourceManager.GetString("Settings.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Settings_Enabled {
            get {
                return ResourceManager.GetString("Settings.Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Airplane mode Flyout.
        /// </summary>
        public static string Settings_EnableModule_Airplane {
            get {
                return ResourceManager.GetString("Settings.EnableModule.Airplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Audio Flyout.
        /// </summary>
        public static string Settings_EnableModule_Audio {
            get {
                return ResourceManager.GetString("Settings.EnableModule.Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Brightness Flyout.
        /// </summary>
        public static string Settings_EnableModule_Brightness {
            get {
                return ResourceManager.GetString("Settings.EnableModule.Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Lock keys Flyout.
        /// </summary>
        public static string Settings_EnableModule_LockKeys {
            get {
                return ResourceManager.GetString("Settings.EnableModule.LockKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout background opacity.
        /// </summary>
        public static string Settings_FlyoutBackgroundOpacity {
            get {
                return ResourceManager.GetString("Settings.FlyoutBackgroundOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout default position.
        /// </summary>
        public static string Settings_FlyoutDefaultPosition {
            get {
                return ResourceManager.GetString("Settings.FlyoutDefaultPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the position in &apos;X,Y&apos; format (Default: 50,60).
        /// </summary>
        public static string Settings_FlyoutDefaultPositionDescription {
            get {
                return ResourceManager.GetString("Settings.FlyoutDefaultPositionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout theme.
        /// </summary>
        public static string Settings_FlyoutTheme {
            get {
                return ResourceManager.GetString("Settings.FlyoutTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout timeout (ms).
        /// </summary>
        public static string Settings_FlyoutTimeout {
            get {
                return ResourceManager.GetString("Settings.FlyoutTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout TopBar.
        /// </summary>
        public static string Settings_FlyoutTopBar {
            get {
                return ResourceManager.GetString("Settings.FlyoutTopBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required to apply language change properly.
        /// </summary>
        public static string Settings_LanguageDescription {
            get {
                return ResourceManager.GetString("Settings.LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Settings_Left {
            get {
                return ResourceManager.GetString("Settings.Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flyout Modules.
        /// </summary>
        public static string Settings_Modules {
            get {
                return ResourceManager.GetString("Settings.Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airplane mode.
        /// </summary>
        public static string Settings_Modules_Airplane {
            get {
                return ResourceManager.GetString("Settings.Modules.Airplane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Settings_Modules_Audio {
            get {
                return ResourceManager.GetString("Settings.Modules.Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Settings_Modules_Audio_Media {
            get {
                return ResourceManager.GetString("Settings.Modules.Audio.Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Settings_Modules_Audio_Volume {
            get {
                return ResourceManager.GetString("Settings.Modules.Audio.Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Settings_Modules_Brightness {
            get {
                return ResourceManager.GetString("Settings.Modules.Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock keys.
        /// </summary>
        public static string Settings_Modules_LockKeys {
            get {
                return ResourceManager.GetString("Settings.Modules.LockKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Settings_Off {
            get {
                return ResourceManager.GetString("Settings.Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string Settings_On {
            get {
                return ResourceManager.GetString("Settings.On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string Settings_Personalization {
            get {
                return ResourceManager.GetString("Settings.Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset all settings to defaults.
        /// </summary>
        public static string Settings_ResetToDefaults {
            get {
                return ResourceManager.GetString("Settings.ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required to apply some changes.
        /// </summary>
        public static string Settings_RestartRequired {
            get {
                return ResourceManager.GetString("Settings.RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Settings_Right {
            get {
                return ResourceManager.GetString("Settings.Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run at startup.
        /// </summary>
        public static string Settings_RunAtStartup {
            get {
                return ResourceManager.GetString("Settings.RunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default.
        /// </summary>
        public static string Settings_SystemDefault {
            get {
                return ResourceManager.GetString("Settings.SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopBar visibility.
        /// </summary>
        public static string Settings_TopBarVisibility {
            get {
                return ResourceManager.GetString("Settings.TopBarVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show icon on system tray area.
        /// </summary>
        public static string Settings_TrayIconEnabled {
            get {
                return ResourceManager.GetString("Settings.TrayIconEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use colored tray icon.
        /// </summary>
        public static string Settings_UseColoredTrayIcon {
            get {
                return ResourceManager.GetString("Settings.UseColoredTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsItem {
            get {
                return ResourceManager.GetString("SettingsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open settings window.
        /// </summary>
        public static string SettingsItemDescription {
            get {
                return ResourceManager.GetString("SettingsItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin TopBar.
        /// </summary>
        public static string UnpinTopBar {
            get {
                return ResourceManager.GetString("UnpinTopBar", resourceCulture);
            }
        }
    }
}
